# Generated by Django 3.2 on 2025-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True, verbose_name='用户名')),
                ('fansCount', models.BigIntegerField(blank=True, null=True, verbose_name='粉丝数量')),
                ('description', models.TextField(blank=True, null=True, verbose_name='视频描述')),
                ('aweme_id', models.TextField(blank=True, null=True, verbose_name='视频id')),
                ('publishTime', models.TextField(blank=True, null=True, verbose_name='发表时间')),
                ('duration', models.TextField(blank=True, null=True, verbose_name='视频时长')),
                ('likeCount', models.TextField(blank=True, null=True, verbose_name='点赞数量')),
                ('collectCount', models.TextField(blank=True, null=True, verbose_name='收藏数量')),
                ('commentCount', models.TextField(blank=True, null=True, verbose_name='评论数量')),
                ('shareCount', models.TextField(blank=True, null=True, verbose_name='分享数量')),
                ('downloadCount', models.TextField(blank=True, null=True, verbose_name='下载数量')),
            ],
            options={
                'verbose_name': '视频信息',
                'db_table': 'videodata',
            },
        ),
    ]
