# Generated by Django 3.2 on 2025-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20250808_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.BigIntegerField(blank=True, null=True, verbose_name='用户id')),
                ('username', models.TextField(blank=True, null=True, verbose_name='用户名')),
                ('commentTime', models.TextField(blank=True, null=True, verbose_name='评论时间')),
                ('userIP', models.TextField(blank=True, null=True, verbose_name='IP地址')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('likeCount', models.BigIntegerField(blank=True, null=True, verbose_name='点赞数量')),
                ('aweme_id', models.BigIntegerField(blank=True, null=True, verbose_name='视频id')),
            ],
            options={
                'verbose_name': '评论信息',
                'db_table': 'commentdata',
            },
        ),
    ]
