# Generated by Django 3.2 on 2025-08-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户数据'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
